#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/ntpd.conf

case "$1" in
	start)
		msg_busy "Starting NTP Client"
		if /usr/bin/ntpd -q ${NTP_CLIENT_OPTION} &>/dev/null; then
			dmn_add ntpdate
			msg_ok
		else
			msg_fail
			exit 1
		fi
		;;
	stop)
		msg_busy "Stopping NTP Client"
		dmn_rm ntpdate
		msg_ok
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "usage: $0 {start|stop|restart}"
esac
