#!/bin/sh
exec 2>&1

PATH=/command:/sbin:/bin:/usr/sbin:/usr/bin

source /etc/runit/start.conf
source /etc/runit/runitfunctions


echo 'Waiting for services to stop...'
sv -w196 force-stop /etc/service/*
sv exit /etc/service/*

echo 'Shutdown...'


# avoid staircase effect
stty onlcr

msg_headline "Initiating Shutdown..."

################################## 1 ##################################
# saving random seed
exec_cmd "Saving random seed" int_urandom_save

################################## 1 ##################################
# time zone (ending)
if [ -n "${TIME_ZONE}" ]; then
    exec_cmd "Setting time zone: ${TIME_ZONE}" int_timezone_set "${TIME_ZONE}"
elif [ -f "/etc/localtime" ];then
    exec_cmd "Dumping /etc/localtime" rm /etc/localtime
fi

################################## 1 ##################################
# Write to wtmp file before unmounting
halt -w

################################## 1 ##################################
# stop lvm
# stop monitoring of LVM2 groups before unmounting filesystems
# Maybe someone has LVM on an encrypted block device
# executing an extra vgchange is errorless
if [ "${USE_LVM}" = "yes" ];then
    exec_cmd "Deactivating monitoring of LVM2 groups" vgchange --monitor n
    exec_cmd "Deactivating LVM2 groups" vgchange --sysinit --activate n
fi

################################## 1 ##################################
# stop udev
# any future uevents can and should be ignored
exec_cmd "Shutting down UDev" udevadm control --exit

################################## 1 ##################################
# kill all processes
exec_cmd "Sending SIGTERM To processes" int_killall_wait 15 40
    
if [ "${?}" = "0" ];then
    exec_cmd "Sending SIGKILL To processes" int_killall_wait 9 60
fi

################################## 1 ##################################
# unmount tmpfs
if [ ${USE_SWAP} = "yes" ];then
    # unmount any non-API partitions that are backed by swap, we don't want to
    # move their contents into memory (waste of time and might caues OOM).
    exec_cmd "Unmounting Swap-backend Filesystems" int_umount_all "tmpfs"
    exec_cmd "Deactivating Swap" swapoff --all
fi

################################## 1 ##################################
# non-API Filesystems
exec_cmd "Unmounting non-API Filesystems" int_umount_all


exec_cmd "Remounting Root filesystem read-only" mount --options remount,ro /

# Power off or reboot
if [ -x /etc/runit/reboot ]; then
	msg_headline "REBOOTING"
	# if kexec is installed and a kernel is loaded, use it
	[[ -x $(type -P kexec) ]] && kexec -e
	reboot -d -f -i
else
	msg_headline "POWER OFF"
	poweroff -d -f -h -i
fi

