#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/rsyslog

PID=`pidof -o %PPID /usr/sbin/rsyslogd`
case "$1" in
  start)
    msg_busy "Starting RSyslogd"
    [ -z "$PID" ] && /usr/sbin/rsyslogd $RSYSLOGD_ARGS
    if [ $? -gt 0 ]; then
      msg_fail
    else
      dmn_add rsyslogd
      msg_ok
    fi
    ;;
  stop)
    msg_busy "Stopping RSyslogd"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      msg_fail
    else
      rm -f /var/run/rsyslogd.pid
      rm -f /var/rsyslogd.persist
      dmn_rm rsyslogd
      msg_ok
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
