#!/bin/bash

# general config
. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/sbin/krb5kdc`
case "$1" in
    start)
        msg_busy "Starting Kerberos Authentication"
        if [ -z "$PID" ]; then
           /usr/sbin/krb5kdc
        fi
        if [ ! -z "$PID" -o $? -gt 0 ]; then
            msg_fail
        else
            dmn_add krb5-kdc
            msg_ok
        fi
        ;;
    stop)
        msg_busy "Stopping Kerberos Authentication"
	    [ ! -z "$PID" ] && kill $PID &> /dev/null
        if [ $? -gt 0 ]; then
            msg_fail
        else
            dmn_rm krb5-kdc
            msg_ok
        fi
        ;;
    restart)
        $0 stop
	sleep 1
        $0 start
        ;;
    *)
        echo "usage: $0 {start|stop|restart}"
	;;
esac
exit 0
