#!/bin/dash
exec 2>/dev/null 1>/dev/null
sv stop irexec || exit 1
/bin/lsmod | grep -q lirc_sir && /sbin/rmmod lirc_sir || exit 1
/bin/lsmod | grep -q lirc_dev && /sbin/rmmod lirc_dev || exit 1
/usr/bin/setserial /dev/ttyS1 uart none port 0x2f8 irq 3 || exit 1
exit 0
