#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    msg_busy "Starting laptop-mode"
    [ ! -d /var/run/laptop-mode-tools ] && install -d /var/run/laptop-mode-tools
    touch /var/run/laptop-mode-tools/enabled
    /usr/sbin/laptop_mode auto >/dev/null 2>&1
    if [ $? -gt 0 ]; then
      msg_fail
    else
      dmn_add laptop-mode
      msg_ok
    fi
    ;;
  stop)
    msg_busy "Stopping laptop-mode"
    rm -f /var/run/laptop-mode-tools/enabled
    /usr/sbin/laptop_mode stop >/dev/null 2>&1
    if [ $? -gt 0 ]; then
      msg_fail
    else
      dmn_rm laptop-mode
      msg_ok
    fi
    ;;
  restart)
    msg_busy "Restarting laptop-mode"
    rm -f /var/run/laptop-mode-tools/enabled
    /usr/sbin/laptop_mode stop >/dev/null 2>&1

    if [ $? -gt 0 ]; then
      msg_fail
      dmn_rm laptop-mode
    else
      rm -f /var/run/laptop-mode-tools/*
      touch /var/run/laptop-mode-tools/enabled
      /usr/sbin/laptop_mode auto force >/dev/null 2>&1
      if [ $? -gt 0 ]; then
        msg_fail
        dmn_rm laptop-mode
      else
        msg_ok
      fi
    fi
    ;;
  exec_cmd)
    /usr/sbin/laptop_mode exec_cmd
    ;;
  *)
      echo "Usage: $0 {stop|start|restart|exec_cmd}"
    ;;
esac
exit 0
