#!/bin/bash

daemon_bin="/usr/lib/git-core/git-daemon"
daemon_name=$(basename $daemon_bin)
PIDF="/var/run/$daemon_name.pid"

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/$daemon_name.conf

get_pid() {
	pidof -o %PPID $daemon_name
}

case "$1" in
  start)
    msg_busy "Starting $daemon_name daemon"

    PID=$(get_pid)
    if [ -z "$PID" ]; then
      [ -f $PIDF ] && rm -f $PIDF
      # RUN
      $daemon_bin --pid-file=$PIDF $GIT_DAEMON_ARGS
      #
      if [ $? -gt 0 ]; then
        msg_fail
        exit 1
      else
        echo $(get_pid) > $PIDF
        dmn_add $daemon_name
        msg_ok
      fi
    else
      msg_fail
      exit 1
    fi
    ;;

  stop)
    msg_busy "Stopping $daemon_name daemon"
    PID=$(get_pid)
    # KILL
    [ ! -z "$PID" ] && kill $PID &> /dev/null
    #
    if [ $? -gt 0 ]; then
      msg_fail
      exit 1
    else
      rm -f $PIDF &> /dev/null
      dmn_rm $daemon_name
      msg_ok
    fi
    ;;

  restart)
    $0 stop
    sleep 3
    $0 start
    ;;

  exec_cmd)
    msg_busy "Checking $daemon_name exec_cmd";
    ck_exec_cmd $daemon_name
    ;;

  *)
    echo "usage: $0 {start|stop|restart|exec_cmd}"
esac

exit 0
