kernel_version=3.4.14-zen
kernel_name=linux-zen

post_install() {
echo -e "
 >> Kernel version: ${kernel_version}

 >> Updating module dependencies
"
depmod ${kernel_version}

echo -e " >> Generating initial ramdisks using mkinitcpio
"
mkinitcpio -p ${kernel_name}

echo -e " >> Contact
     If you have any suggestions to improve zen-sources,
     feel free to join #zen-sources on irc.rizon.net
"
}

post_upgrade() {
	post_install ${@}
}
